# Generated by Django 4.1.7 on 2023-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(max_length=100),
        ),
    ]
