# Generated by Django 4.2 on 2023-04-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_lat_alter_place_lon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='number',
            new_name='order',
        ),
    ]
