# Generated by Django 4.2 on 2023-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name_plural': 'places'},
        ),
        migrations.RemoveField(
            model_name='image',
            name='order',
        ),
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
