# Generated by Django 4.2 on 2023-04-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['pk']},
        ),
    ]
