# Generated by Django 4.2 on 2023-04-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(unique=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lat', 'lon')},
        ),
    ]
