# Generated by Django 4.2 on 2023-04-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_image_file_alter_place_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'image_file')},
        ),
    ]
