# Generated by Django 4.2 on 2023-04-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_image_file_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
