# Generated by Django 4.1 on 2023-08-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер порядка картинки'),
        ),
    ]
